### ISSUE TITLE
Do you have any example(or test) database ?

### ISSUE THREAD

**Issue by dielian8** [groupeLIAMG/bh_tomo#22]
It's hard to realize.
Do you have any example(or test) database ?

**Comment by bernard-giroux** [comment]
Hi,

There is one in the devOOP branch (I suggest that you use this branch for now, until I merge everything in the master).



Le 9 mai 2017 à 21:42, dielian8 <notifications@github.com<mailto:notifications@github.com>> a écrit :


It's hard to realize.
Do you have any example(or test) database ?

**Comment by dielian8** [comment]
Thank you
