### ISSUE TITLE
Problem with loading example in branch devOOP

### ISSUE THREAD

**Issue by Suri81** [groupeLIAMG/bh_tomo#27]
Hi there
I tried to use the test file from devOOP and got an error shown below:
`Error using load
Unable to read MAT-file F:\bh_tomo-master\testConstraints_db.mat. Not a binary MAT-file. Try load -ASCII to read as text.

Error in bh_tomo>OpenMenuItem_Callback (line 186)
load(db_file);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in bh_tomo (line 59)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)bh_tomo('OpenMenuItem_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.`
However, it works fine if I actually use bh_tomo2 inside the devOOP but this one does not have autopick  and time lapse visualizations are not available....
can you please merge them together so that it all works.
many thanks

**Comment by bernard-giroux** [comment]
Looks like the file is corrupted.  Can you try to download it again?

**Comment by Suri81** [comment]
Which one should I download the devOOP or just the main one?

**Comment by Suri81** [comment]
look it is still the same ...auto pick on devOOP is disabled and from the mater folder I cannot import any database!

**Comment by Suri81** [comment]
OK I enabled the Automatic phase picking but it is not working with the test database?
What is a CDM?

**Comment by bernard-giroux** [comment]
Sorry for the confusion.  The auto pick module was added before I started restructuring bh_tomo (the devOOP branch).  I never had time to update that module for the new structure.

(A CDM is a multi-offset gather)
