### ISSUE TITLE
 AIC-CWT Pickers

### ISSUE THREAD

**Issue by Suri81** [groupeLIAMG/bh_tomo#28]
Hi again 
I found your paper entitled "Assisted traveltime picking of crosshole GPR data 
" and it says the AIC-CWT pickers are added to bh_tomo; however I cannot find them or make it work. can you please kindly help me with this.
cheers

**Comment by Suri81** [comment]
Hi again 
I think I have fixed the bug ! 
It was inside ARC_CORRECTION
`for i=1:M
    nb_p  = round(1/(delta*Fa(i)));
    nb_p1 = round(1/(3*delta*Fa(i)));
    nb_p2 = round(1.3*nb_p);
 if K-nb_p>0  % I added this because when the index becomes negative it sends an error 
.
.
.
else pc(i)=p(i); %so I said  if the Index is negative just pc(i)=p(i);
        disp('No correction as Index became Neg')

**Comment by dajianba** [comment]
Hi
I'm  looking for examples of using bh_tomo. 
I don't know what should i do for next step after defined the borehole axis and import radar data,even if I have bh_tomo's instructions.
Can you share with me some of your experiences using this toolkit?
Thank you very much.

**Comment by bernard-giroux** [comment]
Next step is to create the grid.

I'm sorry, but I don't have time to give one on one training.
