### ISSUE TITLE
writing SEGY

### ISSUE THREAD

**Issue by Suri81** [groupeLIAMG/bh_tomo#30]
Hi there
There is still an error with write_segy. I did fix the obvious one which was related to lround and changed x to f but now it cannot write and the matlab gets closed and it crashes . 

long int lround(const double f) {
    long int lx = ( f < 0.0 ) ? f - 0.5 : f + 0.5;
    return lx;
}

**Comment by bernard-giroux** [comment]
can you share the data and a code snippet that would allow reproducing the bug?

**Comment by Suri81** [comment]
![error](https://user-images.githubusercontent.com/34054158/35663840-48fab02a-075a-11e8-95d5-e8bd0667fe3c.png)

**Comment by Suri81** [comment]
![error2](https://user-images.githubusercontent.com/34054158/35663906-a1b926a6-075a-11e8-8c0e-2bc62f205218.png)

**Comment by Suri81** [comment]
----------------------------------------------------------------------
          Access violation detected at Thu Feb  1 14:19:20 2018
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Default Encoding    : windows-1252
  Deployed            : false
  Graphics card 1     : NVIDIA ( 0x10de ) NVIDIA Quadro K2000 Version 10.18.13.5362 (2015-7-22)
  Host Name           : C-D-0005473
  MATLAB Architecture : win64
  MATLAB Entitlement ID: 672267
  MATLAB Root         : C:\Program Files\MATLAB\R2017b
  MATLAB Version      : 9.3.0.713579 (R2017b)
  OpenGL              : hardware
  Operating System    : Microsoft Windows 10 Enterprise
  Processor ID        : x86 Family 6 Model 45 Stepping 7, GenuineIntel
  Virtual Machine     : Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Version 10.0 (Build 15063)

Fault Count: 1


Abnormal termination:
Access violation

Register State (from fault):
  RAX = 0000000000000000  RBX = 000000000000004e
  RCX = 0000000000000000  RDX = 0000000000000001
  RSP = 00000000043fb308  RBP = 00000000043fb390
  RSI = 00000000043fc740  RDI = 00000000ae1d6209
 
   R8 = ffffffff0729f4a0   R9 = 0000000000000000
  R10 = 00000000ffffffff  R11 = 0000000000000000
  R12 = 000000003e5bd260  R13 = 0000000000000056
  R14 = 0000000135d22c20  R15 = 0000000135d24ea0
 
  RIP = 00000000044f9354  EFL = 00010206
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x00000000044f9354                            bin\win64\pgo\libmx.dll+00562004 mxGetPr+00000000
[  1] 0x00000000ae1d1b7b F:\Latest_bh_tomo-2.0.1\bh_tomo-2.0.1\bh_tomo\write_segy_traces.mexw64+00007035 mexFunction+00001405
[  2] 0x00000000fc60234a                               bin\win64\libmex.dll+00140106 mexRunMexFile+00000314
[  3] 0x00000000fc600d22                               bin\win64\libmex.dll+00134434 mexFeature_mexver+00002146
[  4] 0x00000000fc5ffab7                               bin\win64\libmex.dll+00129719 mexUnlock+00028455
[  5] 0x000000001549ca93                     bin\win64\pgo\m_dispatcher.dll+00117395 Mfh_file::dispatch_fh_impl+00000835
[  6] 0x000000001549c73e                     bin\win64\pgo\m_dispatcher.dll+00116542 Mfh_file::dispatch_fh+00000062
[  7] 0x000000001548a8d8                     bin\win64\pgo\m_dispatcher.dll+00043224 Mfunction_handle::dispatch+00001032
[  8] 0x000000001646794e                            bin\win64\pgo\m_lxe.dll+00227662
[  9] 0x0000000016464571                            bin\win64\pgo\m_lxe.dll+00214385
[ 10] 0x000000001646b3a6                            bin\win64\pgo\m_lxe.dll+00242598
[ 11] 0x000000001646bfb3                            bin\win64\pgo\m_lxe.dll+00245683
[ 12] 0x000000001646dff5                            bin\win64\pgo\m_lxe.dll+00253941
[ 13] 0x000000001646d44f                            bin\win64\pgo\m_lxe.dll+00250959
[ 14] 0x000000001646d822                            bin\win64\pgo\m_lxe.dll+00251938
[ 15] 0x000000001653331b                            bin\win64\pgo\m_lxe.dll+01061659 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00604503
[ 16] 0x000000001653ad46                            bin\win64\pgo\m_lxe.dll+01092934 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00635778
[ 17] 0x000000001653a570                            bin\win64\pgo\m_lxe.dll+01090928 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00633772
[ 18] 0x00000000164ca4d6                            bin\win64\pgo\m_lxe.dll+00632022 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00174866
[ 19] 0x00000000164c9ccd                            bin\win64\pgo\m_lxe.dll+00629965 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00172809
[ 20] 0x00000000164c9be6                            bin\win64\pgo\m_lxe.dll+00629734 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00172578
[ 21] 0x00000000164c35a5                            bin\win64\pgo\m_lxe.dll+00603557 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00146401
[ 22] 0x00000000164c3532                            bin\win64\pgo\m_lxe.dll+00603442 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00146286
[ 23] 0x00000000164c71d5                            bin\win64\pgo\m_lxe.dll+00618965 boost::serialization::singleton<boost::archive::detail::pointer_oserializer<boost::archive::binaryTerm_oarchive,MathWorks::lxe::MatlabIrTree> >::get_instance+00161809
[ 24] 0x00000000157f5b63                    bin\win64\pgo\m_interpreter.dll+00416611 inEvalCmdWithLocalReturn+00000063
[ 25] 0x00000000fb60de26                          bin\win64\libmwbridge.dll+00122406 mnParser+00001254
[ 26] 0x00000000155bbdb1                                  bin\win64\mcr.dll+00245169 mcr::runtime::setInterpreterThreadSingletonToCurrent+00029793
[ 27] 0x00000000155bace5                                  bin\win64\mcr.dll+00240869 mcr::runtime::setInterpreterThreadSingletonToCurrent+00025493
[ 28] 0x00000000155bad53                                  bin\win64\mcr.dll+00240979 mcr::runtime::setInterpreterThreadSingletonToCurrent+00025603
[ 29] 0x00000000155bb6e1                                  bin\win64\mcr.dll+00243425 mcr::runtime::setInterpreterThreadSingletonToCurrent+00028049
[ 30] 0x00000000fd02cc77                                  bin\win64\iqm.dll+00642167 iqm::UserEvalPlugin::pre+00028951
[ 31] 0x00000000fd039cfc                                  bin\win64\iqm.dll+00695548 iqm::UserEvalPlugin::pre+00082332
[ 32] 0x00000000fd02737f                                  bin\win64\iqm.dll+00619391 iqm::UserEvalPlugin::pre+00006175
[ 33] 0x00000000fd02cc16                                  bin\win64\iqm.dll+00642070 iqm::UserEvalPlugin::pre+00028854
[ 34] 0x00000000fd027863                                  bin\win64\iqm.dll+00620643 iqm::UserEvalPlugin::pre+00007427
[ 35] 0x00000000fd03c8b6                                  bin\win64\iqm.dll+00706742 iqm::UserEvalPlugin::pre+00093526
[ 36] 0x00000000fd0080f7                                  bin\win64\iqm.dll+00491767 iqm::PackagedTaskPlugin::PackagedTaskPlugin+00000759
[ 37] 0x00000000fd0088bf                                  bin\win64\iqm.dll+00493759 iqm::PackagedTaskPlugin::execute+00000879
[ 38] 0x00000000fd00817d                                  bin\win64\iqm.dll+00491901 iqm::PackagedTaskPlugin::PackagedTaskPlugin+00000893
[ 39] 0x00000000fd008708                                  bin\win64\iqm.dll+00493320 iqm::PackagedTaskPlugin::execute+00000440
[ 40] 0x00000000fcfdbd3a                                  bin\win64\iqm.dll+00310586 iqm::Iqm::setupIqmFcnPtrs+00079802
[ 41] 0x00000000fcfdbc06                                  bin\win64\iqm.dll+00310278 iqm::Iqm::setupIqmFcnPtrs+00079494
[ 42] 0x00000000fcfbf5be                                  bin\win64\iqm.dll+00193982 iqm::Iqm::deliver+00004046
[ 43] 0x00000000fcfc0545                                  bin\win64\iqm.dll+00197957 iqm::Iqm::deliver+00008021
[ 44] 0x00000001001237c1                        bin\win64\libmwservices.dll+01259457 services::system_events::PpeDispatchHook::dispatchOne+00021505
[ 45] 0x0000000100128663                        bin\win64\libmwservices.dll+01279587 sysq::addProcessPendingEventsUnitTestHook+00002211
[ 46] 0x0000000100128850                        bin\win64\libmwservices.dll+01280080 sysq::addProcessPendingEventsUnitTestHook+00002704
[ 47] 0x0000000100129c26                        bin\win64\libmwservices.dll+01285158 sysq::getCondition+00003462
[ 48] 0x000000010012ac66                        bin\win64\libmwservices.dll+01289318 svWS_ProcessPendingEvents+00000230
[ 49] 0x00000000155bc244                                  bin\win64\mcr.dll+00246340 mcr::runtime::setInterpreterThreadSingletonToCurrent+00030964
[ 50] 0x00000000155bc964                                  bin\win64\mcr.dll+00248164 mcr::runtime::setInterpreterThreadSingletonToCurrent+00032788
[ 51] 0x00000000155b2762                                  bin\win64\mcr.dll+00206690 mcr_process_events+00008818
[ 52] 0x00000000153823c5                             bin\win64\MVMLocal.dll+00271301 mvm_server::inproc::LocalFactory::terminate+00088005
[ 53] 0x00000000fa957669                                  bin\win64\mvm.dll+01209961 mvm::detail::initLocalMvmHack+00000569
[ 54] 0x00000000fa957e2b                                  bin\win64\mvm.dll+01211947 mvm::detail::SessionImpl::privateSession+00000555
[ 55] 0x00000000fa958051                                  bin\win64\mvm.dll+01212497 mvm::detail::SessionImpl::privateSession+00001105
[ 56] 0x0000000140007833                               bin\win64\MATLAB.exe+00030771
[ 57] 0x000000014000863f                               bin\win64\MATLAB.exe+00034367
[ 58] 0x00007ff8aed02774                   C:\Windows\System32\KERNEL32.DLL+00075636 BaseThreadInitThunk+00000020
[ 59] 0x00007ff8af990d51                      C:\Windows\SYSTEM32\ntdll.dll+00462161 RtlUserThreadStart+00000033


This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.

If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.** This crash report has been saved to disk as C:\Users\268523d\AppData\Local\Temp\matlab_crash_dump.6840-1 **


Caught MathWorks::System::FatalException
[Please exit and restart MATLAB]>>

**Comment by bernard-giroux** [comment]
I'm sorry but I can't reproduce the bug on my machine if I don't have access to your data and the sequence of command that triggers the bug
