### ISSUE TITLE
how can i do t0 correction?

### ISSUE THREAD

**Issue by gsmamarsaikhan** [groupeLIAMG/bh_tomo#31]
I am using your matlab package (bh_tomo). actually all of the versions doesn't work on macbook. it works well in windows platform. Also, I can not do t0 pick up and t0 correction? How can i do that? Thank you

**Comment by bernard-giroux** [comment]
Sorry but what do you mean by all of the versions?

You have to pick t0 on air shots in the manual travel time picking module.

**Comment by dajianba** [comment]
Hello，I am using your matlab package(bh_tomo).Even if I read the instructions, I don 't know how to use the package（my English is not well）.Do you have a video of how to use this package?Thanks
